camera_name: legwheel_rgbd
depth_registration: true
align_mode: SW
align_target_stream: COLOR
enable_color: true
enable_depth: true
enable_left_ir: false
enable_right_ir: false
enable_accel: true
enable_gyro: true
enable_sync_output_accel_gyro: true
accel_rate: 100hz
gyro_rate: 100hz
enable_point_cloud: false
enable_colored_point_cloud: false
publish_tf: true
tf_publish_rate: 0.0
enable_frame_sync: true
enable_sync_host_time: true
enable_depth_scale: true
enable_noise_removal_filter: true
enable_disparity_to_depth: true
color_width: 0
color_height: 0
color_fps: 0
depth_width: 0
depth_height: 0
depth_fps: 0
